ci: only allow releasing and deploying to dev

diff --git a/.github/workflows/release-package-manual.yml b/.github/workflows/release-package-manual.yml
--- a/.github/workflows/release-package-manual.yml
+++ b/.github/workflows/release-package-manual.yml
@@ -6,19 +6,27 @@ on:
   workflow_dispatch:
     inputs:
       tag:
-        description: "The NPM tag to apply to the release. Use 'latest' for Production release."
-        required: false
         type: string
         default: "dev"
 
 env:
   NX_ISOLATE_PLUGINS: false
-  PREID: ${{ inputs.tag != 'latest' && inputs.tag ||  ''  }}
   TAG: ${{ inputs.tag ||  'dev'  }}
 
 jobs:
+  validate-tag:
+    name: Validate Tag
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check tag value
+        if: ${{ inputs.tag == 'staging' || inputs.tag == 'production' || inputs.tag == 'latest' }}
+        run: |
+          echo "::error::Tag value '${{ inputs.tag }}' is not allowed"
+          exit 1
+
   build-and-publish:
     name: Build and Publish Package
+    needs: validate-tag
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -62,7 +70,7 @@ jobs:
           git config user.email "-"
 
       - name: Update pkg version
-        run: pnpm nx release --projects='packages/*,apps/connect,clis/*' --skip-publish --preid=${{ env.PREID }}
+        run: pnpm nx release --projects='packages/*,apps/connect,clis/*' --skip-publish --preid=${{ env.TAG }}
         shell: bash
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
